<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace GPBMetadata\Proto;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab6010a1070726f746f2f757365722e70726f746f1203727063222e0a0c" .
            "4c6f67696e52657175657374120c0a046e616d6518012001280912100a08" .
            "70617373776f7264180220012809222d0a0d4c6f67696e526573706f6e73" .
            "65120c0a046e616d65180120012809120e0a0667656e6465721802200128" .
            "0932360a0455736572122e0a054c6f67696e12112e7270632e4c6f67696e" .
            "526571756573741a122e7270632e4c6f67696e526573706f6e7365620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

