// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"book/service/user/rpc/internal/logic"
	"book/service/user/rpc/internal/svc"
	rpc "book/service/user/rpc/rpc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *rpc.LoginRequest) (*rpc.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
